create table CambioResultado (id_cambio_resultado integer not null auto_increment, fecha_cambio date, gano_local_desempate bit, jugo_local bit, jugo_visitante bit, equipo_local integer, equipo_visitante integer, id_resultado integer, primary key (id_cambio_resultado));
create table Competencia (id_competencia integer not null auto_increment, acepta_empates bit, cant_sets integer, eliminada bit, Estado integer, fecha_elim date, modalidad integer, nom_comp varchar(255), pts_part_empatado integer, pts_partido_ganado integer, pts_por_presentarse integer, reglas_comp TEXT, sistemaPuntuacion integer, tantos_a_favor_por_no_presentarse integer, id_deporte integer, id_fixture integer, id_usuario integer, primary key (id_competencia));
create table Deporte (id_deporte integer not null auto_increment, nom_deporte varchar(255), primary key (id_deporte));
create table Disponibilidad (id_disponibilidad integer not null auto_increment, disponibilidad integer, codigo_lugar integer, id_competencia integer, primary key (id_disponibilidad));
create table Fecha (id_fecha integer not null auto_increment, numero_fecha integer, ronda integer, id_fixture integer, primary key (id_fecha));
create table Fixture (id_fixture integer not null auto_increment, primary key (id_fixture));
create table InicioSesion (id_inicio_sesion integer not null auto_increment, fecha_elim date, ip varchar(255), primary key (id_inicio_sesion));
create table Localidad (id_localidad integer not null auto_increment, nombre_localidad varchar(255), id_provincia integer, primary key (id_localidad));
create table LugarDeRealizacion (id_lugar integer not null auto_increment, codigo_lugar varchar(255), descripcion_lugar varchar(255), eliminado bit, fecha_elim date, nom_lugar varchar(255), id_usuario integer, primary key (id_lugar));
create table ModificacionParticipante (id_modif_participante integer not null auto_increment, email varchar(255), fecha_modificacion date, Imagen longblob, nombre_participante varchar(255), id_participante integer, primary key (id_modif_participante));
create table Pais (id_pais integer not null auto_increment, nombre_pais varchar(255), primary key (id_pais));
create table Participante (id_participante integer not null auto_increment, email_partic varchar(255), esLibre bit not null, Imagen longblob, nom_partic varchar(255), id_competencia integer, primary key (id_participante));
create table Partido (id_partido integer not null auto_increment, es_libre bit, tipo_ref_partido integer, id_participante integer, codigo_lugar integer, id_fecha integer, primary key (id_partido));
create table PartidosLocales (id_participante integer, id_partido integer not null, primary key (id_partido));
create table PartidosVisitantes (id_participante integer, id_partido integer not null, primary key (id_partido));
create table Provincia (id_provincia integer not null auto_increment, nombre_provincia varchar(255), id_pais integer, primary key (id_provincia));
create table Resultado (id_resultado integer not null auto_increment, gano_local_desempate bit, jugo_local bit, jugo_visitante bit, equipo_local integer, equipo_visitante integer, id_partido integer, primary key (id_resultado));
create table Usuario (id_usuario integer not null auto_increment, apellido varchar(255), email varchar(255), nombre varchar(255), num_doc varchar(255), password varchar(255), tipo_doc integer, id_inicio_sesion integer, id_localidad integer, primary key (id_usuario));
create table se_practica_en (id_deporte integer not null, id_lugar integer not null);
alter table CambioResultado add constraint FK_hsp6ltalc2lkxxulbci23r77l foreign key (id_resultado) references Resultado (id_resultado);
alter table Competencia add constraint FK_68kjojs2gpt8thuf3q2dt3x4o foreign key (id_deporte) references Deporte (id_deporte);
alter table Competencia add constraint FK_ff6yjqt48v2iqyikb1fy10s3w foreign key (id_fixture) references Fixture (id_fixture);
alter table Competencia add constraint FK_btnvhe39i58bpyvlyber0da0u foreign key (id_usuario) references Usuario (id_usuario);
alter table Disponibilidad add constraint FK_7s2o872ftypt4ajh8mxr4o0gw foreign key (codigo_lugar) references LugarDeRealizacion (id_lugar);
alter table Disponibilidad add constraint FK_2qmqqhac889awdefo1d3h2c0k foreign key (id_competencia) references Competencia (id_competencia);
alter table Fecha add constraint FK_5hbam6evhu02ae59cw2egs88 foreign key (id_fixture) references Fixture (id_fixture);
alter table Localidad add constraint FK_2elhvaur3hsux4tkpyya0mekg foreign key (id_provincia) references Provincia (id_provincia);
alter table LugarDeRealizacion add constraint FK_471gtymhrp4721a86gqkc0wpa foreign key (id_usuario) references Usuario (id_usuario);
alter table ModificacionParticipante add constraint FK_sr9j4n11m2kd2o54ykbeekiej foreign key (id_participante) references Participante (id_participante);
alter table Participante add constraint FK_dl235snmpydepdpxas2inwy13 foreign key (id_competencia) references Competencia (id_competencia);
alter table Partido add constraint FK_9a30bxad569w3x2iqbs3v5ia3 foreign key (id_participante) references Participante (id_participante);
alter table Partido add constraint FK_26kpipv12gftwxve110buockl foreign key (codigo_lugar) references LugarDeRealizacion (id_lugar);
alter table Partido add constraint FK_9xxwkld5n3vksvkxolhjiycwj foreign key (id_fecha) references Fecha (id_fecha);
alter table PartidosLocales add constraint FK_94mxeg7yn7n9545nfhlgtirca foreign key (id_participante) references Participante (id_participante);
alter table PartidosLocales add constraint FK_2esyll1ikisclijn3lfa8ivg8 foreign key (id_partido) references Partido (id_partido);
alter table PartidosVisitantes add constraint FK_o2yqj3wiof51sdls0gvmyj1ue foreign key (id_participante) references Participante (id_participante);
alter table PartidosVisitantes add constraint FK_pdmhvqd2ijp2c7dak4yx8txrq foreign key (id_partido) references Partido (id_partido);
alter table Provincia add constraint FK_kjsc0a5y86tbh0jbu4q4p0gq3 foreign key (id_pais) references Pais (id_pais);
alter table Resultado add constraint FK_p62xg1cad66r06x8n9x956eqf foreign key (id_partido) references Partido (id_partido);
alter table Usuario add constraint FK_g27o6ognkovmov4hlj3gvqbxr foreign key (id_inicio_sesion) references InicioSesion (id_inicio_sesion);
alter table Usuario add constraint FK_lxj3pu3vu99recchqm4evud foreign key (id_localidad) references Localidad (id_localidad);
alter table se_practica_en add constraint FK_9ky8je0h2bxbwf6djs0ey6ncs foreign key (id_lugar) references LugarDeRealizacion (id_lugar);
alter table se_practica_en add constraint FK_18k1jbl4hjngx0xcl1845vjis foreign key (id_deporte) references Deporte (id_deporte);
